In [1]:
import os
import json
import numpy as np
import pandas as pd
from collections import defaultdict
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans
from sklearn.mixture import GaussianMixture
from sklearn.metrics import silhouette_score
import matplotlib.pyplot as plt

In [2]:
df_features = pd.read_csv('scaled_songs.csv')
print(df_features.head)

<bound method NDFrame.head of                             id  danceability    energy       key  loudness  \
0       7lmeHLHBe4nmXzuXc0HDjk     -0.239643  1.545439  0.504262  0.855004   
1       1wsRitfRRtWyEapl0q22o8      0.448997  1.470214  1.632828  0.794662   
2       1hR0fIFK2qRG3f3RF70pb7     -1.067078  1.516782  0.504262  0.850871   
3       2lbASgTSoDO7MTuLAXlTW0     -0.399791  1.506035  1.632828  0.783751   
4       1MQTmpYOZ6fcMQc56Hdo7T     -0.474528  1.369913 -0.906446  0.635127   
...                        ...           ...       ...       ...       ...   
134707  0tOyrixMQ17NUznPIxYtVD      1.644775 -0.310129  1.068545  0.406157   
134708  4mjGy5qFexa73Bwdo50dWk      1.132299  0.764524 -0.906446  0.664720   
134709  4XQprvwbCyAb7k9ETF0Udn      0.219450 -0.825963 -0.906446 -0.372176   
134710  63C7ypxBOdeUSAQsoulDoO     -0.522572  0.657059  1.350686  0.751679   
134711  4GMAChvptmrvOS0pnP7oay      0.651852  1.011695  1.068545  1.087116   

        speechiness  acousticness

In [16]:
np_features = df_features.to_numpy() 
print(np_features.shape)
np_features_copy = np_features[:,1:]
print(np_features_copy.shape)

(134712, 12)
(134712, 11)


In [17]:
import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np

from sklearn import datasets
from sklearn.preprocessing import MinMaxScaler
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from sklearn.model_selection import cross_val_predict

from sklearn.decomposition import PCA
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis 
from sklearn.manifold import TSNE
from sklearn.cluster import KMeans

In [ ]:
# Using Pca to decrease the dimension
pca = PCA(n_components=5)
X_pca = pca.fit_transform(np_features_copy)
print(X_pca[:5,:])

[[-1.96210933 -0.7600901   0.11397433  1.12737109  2.27210076]
 [-2.12941691  0.37746909  0.19882264  0.37648318  3.29836101]
 [-2.01111087 -0.93674442  1.79391519 -0.1993902   0.86890995]
 [-1.69670956  0.05878575  0.78746524 -1.25357575  1.06985496]
 [-1.46229385 -0.70737473 -0.90926728  1.36577121  0.47064951]]


In [ ]:
gmm = GaussianMixture(n_components=10, covariance_type='full', random_state=42)

gmm.fit(X_pca)

labels = gmm.predict(X_pca)

probs = gmm.predict_proba(X_pca)

print("Predict label for every data point:", labels)
print("The posterior probability of each data point is:\n", probs)

Predict label for every data point： [6 7 6 ... 9 4 4]
The posterior probability of each data point is:
 [[3.99577985e-072 6.11277223e-223 2.73901774e-114 ... 2.07880365e-001
  7.85052725e-077 2.69448140e-078]
 [1.79759221e-101 0.00000000e+000 1.55180060e-174 ... 6.25883197e-001
  1.96375605e-107 1.41646460e-125]
 [9.30735636e-002 3.46994629e-057 7.36083578e-015 ... 6.57996991e-004
  1.45037461e-003 1.92065482e-027]
 ...
 [4.94921033e-006 2.96076936e-002 2.09038649e-003 ... 1.31584566e-005
  2.42045751e-005 9.50486589e-001]
 [3.93372301e-002 2.60012674e-023 3.26957742e-024 ... 1.86024171e-004
  7.99883031e-003 6.44368567e-008]
 [3.34154675e-001 4.62661484e-024 5.02026440e-017 ... 1.42034594e-004
  3.56364674e-003 2.27204912e-007]]


In [20]:
print(len(labels))

134712


In [ ]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix

# Assume np_features_copy is your original normalized data, labels is the pseudo-labels obtained by clustering

# Divide the dataset: 80% training, 20% testing
X_train, X_test, y_train, y_test = train_test_split(np_features_copy, labels, test_size=0.2, random_state=42)

# Build and train a random forest model
clf = RandomForestClassifier(n_estimators=100, random_state=42)
clf.fit(X_train, y_train)

# Predict test set results
y_pred = clf.predict(X_test)

# Output evaluation results
print("Classification Report:")
print(classification_report(y_test, y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Classification Report:
              precision    recall  f1-score   support

           0       0.91      0.89      0.90      3524
           1       0.95      0.95      0.95      3112
           2       0.91      0.90      0.90      1957
           3       0.92      0.91      0.92      2243
           4       0.89      0.88      0.88      2391
           5       0.92      0.91      0.92      4033
           6       0.91      0.91      0.91       621
           7       0.98      0.96      0.97       193
           8       0.96      0.80      0.88       395
           9       0.91      0.94      0.93      8474

    accuracy                           0.92     26943
   macro avg       0.93      0.91      0.92     26943
weighted avg       0.92      0.92      0.92     26943

Confusion Matrix:
[[3119    5    0    2  108   65    8    0    0  217]
 [   3 2950    0    5    0    5    0    0    0  149]
 [   0    0 1758   80    6   46    1    0    0   66]
 [   1    5   71 2047    1   19   19    0

In [ ]:
from sklearn.svm import SVC

# Build and train the SVM model (the RBF kernel function is used here, and the kernel function and parameters can be adjusted according to the data)
svm_clf = SVC(kernel='rbf', C=1.0, gamma='scale', random_state=42)
svm_clf.fit(X_train, y_train)

# Predict test set results
y_pred = svm_clf.predict(X_test)

# Output evaluation results
print("Classification Report:")
print(classification_report(y_test, y_pred))
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

Classification Report:
              precision    recall  f1-score   support

           0       0.95      0.94      0.94      3524
           1       0.95      0.98      0.97      3112
           2       0.93      0.93      0.93      1957
           3       0.94      0.94      0.94      2243
           4       0.94      0.94      0.94      2391
           5       0.96      0.95      0.96      4033
           6       0.97      0.89      0.93       621
           7       0.98      0.99      0.99       193
           8       0.99      0.93      0.96       395
           9       0.94      0.95      0.95      8474

    accuracy                           0.95     26943
   macro avg       0.96      0.94      0.95     26943
weighted avg       0.95      0.95      0.95     26943

Confusion Matrix:
[[3298    3    0    3   57   18    2    0    0  143]
 [   3 3046    0    4    0    2    0    0    0   57]
 [   0    0 1829   42    1   36    0    0    1   48]
 [   1    8   44 2105    0   11    5    0

In [33]:
from sklearn.neighbors import NearestNeighbors
import numpy as np
from sklearn.preprocessing import StandardScaler

# pick one from dataset
new_data = np_features_copy[2,:]
print('input data:',new_data)
new_data = new_data.reshape(1, -1)

# using PCA to decrease dimension
new_data_pca = pca.transform(new_data)
predicted_label = gmm.predict(new_data_pca)[0]
print('predicted_label is:', predicted_label)

# select all data belong to this labels
cluster_indices = np.where(labels == predicted_label)[0]
cluster_data = X_pca[cluster_indices]

input data: [-1.067078059953224 1.5167818407892877 0.5042616931496741
 0.8508713851510616 3.770628025370261 -1.0260241288695873
 -0.6630537914880389 -0.4539203864778992 -0.310891973773382
 1.0131286944249982 0.4078874580558583]
predicted_label is: 6


In [34]:
# using nearest neighbor search
nbrs = NearestNeighbors(n_neighbors=10, metric='euclidean')
nbrs.fit(cluster_data)
distances, local_indices = nbrs.kneighbors(new_data_pca)


In [35]:
recommended_indices = cluster_indices[local_indices[0]]
print("Recommended indices:", recommended_indices)
print("Corresponding distances:", distances)

Recommended indices: [     2  90574  11710  79843  64898  86477  87519 128226 123664  64899]
Corresponding distances: [[3.74874971e-13 2.61721940e-01 4.91084217e-01 7.81120559e-01
  8.52213984e-01 8.73760681e-01 8.92696023e-01 9.25220217e-01
  9.29999141e-01 9.48203163e-01]]


In [ ]:
import pandas as pd

# Assume X_pca is your dimensionally reduced data, with a shape of (n_samples, 5)
# Specify column names for each principal component (can be adjusted based on actual conditions)
columns = ["PC1", "PC2", "PC3", "PC4", "PC5"]

# create DataFrame
df_pca = pd.DataFrame(X_pca, columns=columns)

# Save as CSV file without saving row index
df_pca.to_csv("X_pca.csv", index=False)

print("X_pca already save as X_pca.csv")

X_pca 已保存为 X_pca.csv


In [ ]:
columns = ["label"]

# create DataFrame
df_pca = pd.DataFrame(labels, columns=columns)

# Save as CSV file without saving row index
df_pca.to_csv("labels.csv", index=False)

print("labels was saved as labels.csv")

labels 已保存为 labels.csv
